"""Assemble the full evidence-board HTML document from the board sections."""

from __future__ import annotations

from autoalphafold3.ui import panels
from autoalphafold3.ui.components import esc, status_pill
from autoalphafold3.ui.state import UiState

_HEAD = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Auto-AlphaFold3 · Evidence Board</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Fira+Mono:wght@400;500;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="assets/modal.css">
</head>
<body>
"""

_GEAR = (
    '<svg viewBox="0 0 24 24" fill="none"><path d="M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z" stroke="currentColor" stroke-width="1.6"/>'
    '<path d="M19.4 13a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 1 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 1 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 1 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9c.2.61.74 1.05 1.39 1.1H21a2 2 0 1 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1Z" stroke="currentColor" stroke-width="1.4"/></svg>'
)


def _toolbar(s: UiState) -> str:
    badge = '<span class="illus">Sample</span>' if s.is_sample else status_pill("live", "ok")
    return (
        '<header class="topbar"><div class="tb-group"><h1 class="app-name">Auto-AlphaFold3</h1></div>'
        '<div class="tb-group tb-right">'
        '<div class="seg" role="group" aria-label="View">'
        '<button class="seg-btn is-active" type="button">Board</button>'
        '<button class="seg-btn" type="button">Trials</button>'
        '<button class="seg-btn" type="button">Logs</button></div>'
        f'<div class="ctx-pill"><span class="dot-live"></span><span class="ctx-val">{esc(s.split)}</span>'
        f'<span class="ctx-sep">·</span><span class="ctx-val">{esc(s.scorer)}</span>'
        '<svg class="chev" viewBox="0 0 12 12" fill="none"><path d="M3 4.5 6 7.5 9 4.5" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/></svg></div>'
        f'<button class="icon-btn" type="button" aria-label="Settings">{_GEAR}</button>'
        f'{badge}</div></header>'
    )


def render_board(s: UiState) -> str:
    traj_inner, traj_json = panels.trajectory_section(s)
    if s.is_sample:
        foot_left = "Sample data · illustrative, not benchmark results"
    else:
        prov = s.provenance
        foot_left = f"Live · {esc(s.source)} · candidate {esc(prov.get('candidate', ''))} {esc(prov.get('git_sha', ''))}"
    body = (
        '<div class="board">'
        + _toolbar(s)
        + panels.metric_band(s)
        + f'<div class="row two"><div>{traj_inner}</div><div>{panels.cartographer_section(s)}</div></div>'
        + f'<div class="row flush">{panels.ledger_section(s)}</div>'
        + f'<div class="row">{panels.gate_section(s)}</div>'
        + f'<div class="row">{panels.overlay_section(s)}</div>'
        + f'<footer class="board-foot"><span>{foot_left}</span>'
        '<span>Generated by autoalphafold3.ui.build</span></footer>'
        '</div>'
    )
    script = f'<script>window.TRAJ_POINTS = {traj_json};</script>\n<script src="assets/board.js"></script>'
    return _HEAD + body + "\n" + script + "\n</body>\n</html>\n"
