"""Assemble full HTML pages (Board / Trials / Logs) from the board sections."""

from __future__ import annotations

from autoalphafold3.ui import panels
from autoalphafold3.ui.components import esc, status_pill
from autoalphafold3.ui.state import UiState


def _head(title: str) -> str:
    return (
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        '<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
        f"<title>Auto-AlphaFold3 · {esc(title)}</title>\n"
        '<link rel="preconnect" href="https://fonts.googleapis.com">\n'
        '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n'
        '<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Fira+Mono:wght@400;500;700&display=swap" rel="stylesheet">\n'
        '<link rel="stylesheet" href="assets/modal.css">\n</head>\n<body>\n'
    )


def _toolbar(s: UiState, active: str = "Board", board_href: str = "index.html") -> str:
    badge = '<span class="illus">Sample</span>' if s.is_sample else status_pill("live", "ok")
    tabs = (("Board", board_href), ("Trials", "trials.html"), ("Logs", "logs.html"))
    seg = "".join(
        f'<a class="seg-btn{" is-active" if name == active else ""}" href="{href}">{name}</a>'
        for name, href in tabs
    )
    return (
        '<header class="topbar"><div class="tb-group"><h1 class="app-name">Auto-AlphaFold3</h1></div>'
        '<div class="tb-group tb-right">'
        f'<div class="seg" role="group" aria-label="View">{seg}</div>'
        f'<div class="ctx-pill"><span class="dot-live"></span><span class="ctx-val">{esc(s.split)}</span>'
        f'<span class="ctx-sep">·</span><span class="ctx-val">{esc(s.scorer)}</span>'
        '<svg class="chev" viewBox="0 0 12 12" fill="none"><path d="M3 4.5 6 7.5 9 4.5" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/></svg></div>'
        f"{badge}</div></header>"
    )


def _footer(s: UiState) -> str:
    left = "Sample data · illustrative, not benchmark results" if s.is_sample else f"Live · {esc(s.source)}"
    return f'<footer class="board-foot"><span>{left}</span><span>Generated by autoalphafold3.ui.build</span></footer>'


def render_board(s: UiState, board_href: str = "index.html") -> str:
    traj_inner, traj_json = panels.trajectory_section(s)
    body = (
        '<div class="board">'
        + _toolbar(s, "Board", board_href)
        + panels.metric_band(s)
        + f'<div class="row two"><div>{traj_inner}</div><div>{panels.cartographer_section(s)}</div></div>'
        + f'<div class="row flush">{panels.ledger_section(s)}</div>'
        + (f'<div class="row">{panels.hypothesis_section(s)}</div>' if s.hypothesis is not None else "")
        + f'<div class="row">{panels.gate_section(s)}</div>'
        + f'<div class="row">{panels.overlay_section(s)}</div>'
        + _footer(s)
        + "</div>"
    )
    script = f'<script>window.TRAJ_POINTS = {traj_json};</script>\n<script src="assets/board.js"></script>'
    return _head("Evidence Board") + body + "\n" + script + "\n</body>\n</html>\n"


def _subpage(s: UiState, active: str, inner: str, script: str = "", *, flush: bool = False, board_href: str = "index.html") -> str:
    row_cls = "row flush" if flush else "row"
    body = (
        '<div class="board">'
        + _toolbar(s, active, board_href)
        + f'<div class="{row_cls}" style="border-top:0;padding-top:8px">{inner}</div>'
        + _footer(s)
        + "</div>"
    )
    return _head(active) + body + ("\n" + script if script else "") + "\n</body>\n</html>\n"


_FILTER_JS = (
    "<script>\n(function(){var bar=document.querySelector('.filter-bar'),tbl=document.getElementById('trialsTable');"
    "if(!bar||!tbl)return;var rows=tbl.querySelectorAll('tbody tr');bar.addEventListener('click',function(e){"
    "var b=e.target.closest('[data-filter]');if(!b)return;bar.querySelectorAll('[data-filter]').forEach("
    "function(x){x.classList.toggle('is-active',x===b);});var f=b.getAttribute('data-filter');rows.forEach("
    "function(r){r.style.display=(f==='all'||r.getAttribute('data-status')===f)?'':'none';});});})();\n</script>"
)

_SEARCH_JS = (
    "<script>\n(function(){var inp=document.getElementById('logSearch'),feed=document.getElementById('logFeed');"
    "if(!inp||!feed)return;var rows=feed.querySelectorAll('.logrow');inp.addEventListener('input',function(){"
    "var q=inp.value.trim().toLowerCase();rows.forEach(function(r){r.style.display=(!q||"
    "r.getAttribute('data-text').indexOf(q)>=0)?'':'none';});});})();\n</script>"
)


def render_trials(s: UiState, board_href: str = "index.html") -> str:
    return _subpage(s, "Trials", panels.trials_table(s), _FILTER_JS, flush=True, board_href=board_href)


def render_logs(s: UiState, board_href: str = "index.html") -> str:
    return _subpage(s, "Logs", panels.logs_feed(s), _SEARCH_JS, board_href=board_href)
